name: Notion Intensive Monitor
on:
  schedule:
    # 1. 평일(월-금) 09:04 ~ 18:04 KST: 10분 간격
    - cron: '4/10 0-8 * * 1-5'

    # 2. 평일(월-금) 18:13 ~ 21:13 KST: 30분 간격
    - cron: '13,43 9-11 * * 1-5'

    # 3. 주말(토-일) 10:22 ~ 21:22 KST: 1시간 간격
    - cron: '22 1-12 * * 0,6'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run Script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
